/**
 * Viseme categories compatible with Oculus / ARKit / Ready Player Me blendshape standards.
 */
export type VisemeName =
  | 'viseme_sil' // Silence / rest
  | 'viseme_aa'  // 'ah', 'aa' (car, father)
  | 'viseme_E'   // 'eh' (bed, get)
  | 'viseme_I'   // 'ih', 'ee' (it, see)
  | 'viseme_O'   // 'oh' (go, home)
  | 'viseme_U'   // 'oo' (you, food)
  | 'viseme_PP'  // 'p', 'b', 'm' (bilabial)
  | 'viseme_FF'  // 'f', 'v' (labiodental)
  | 'viseme_TH'  // 'th' (dental)
  | 'viseme_DD'  // 't', 'd' (alveolar)
  | 'viseme_kk'  // 'k', 'g' (velar)
  | 'viseme_CH'  // 'ch', 'j', 'sh'
  | 'viseme_SS'  // 's', 'z'
  | 'viseme_nn'  // 'n', 'l'
  | 'viseme_RR'  // 'r'

/**
 * Real-time speech activity state generated by LipSyncAnalyzer.
 */
export interface SpeechActivity {
  isSpeaking: boolean
  amplitude: number         // 0.0 to 1.0 smoothed envelope
  rawAmplitude: number      // instantaneous amplitude
  viseme: VisemeName        // active primary viseme
  visemeWeights: Record<string, number>
  charIndex: number
  elapsedTime: number
}

/**
 * Inspection report on what facial controls the loaded 3D avatar actually possesses.
 */
export interface ModelFacialCapabilities {
  hasMorphTargets: boolean
  hasJawBone: boolean
  morphTargetNames: string[]
  jawBoneName: string | null
  mode: 'morph-target' | 'jaw-bone' | 'cadence-fallback'
  diagnostics: string
}
